name: Discord Webhook

on: [push]

jobs:
  git:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Run Discord Webhook
      uses: DesireHellandr/TestHook@main
      with:
        webhook_url: ${{ secrets.YOUR_DISCORD_WEBHOOK_URL }}
#Test